//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cluster.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cluster.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique identifier for this computer..
        /// </summary>
        public static string AddComputerPage_Name_Description {
            get {
                return ResourceManager.GetString("AddComputerPage.Name.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AddComputerPage_Name_Title {
            get {
                return ResourceManager.GetString("AddComputerPage.Name.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully created..
        /// </summary>
        public static string AddComputerPage_Success_Text {
            get {
                return ResourceManager.GetString("AddComputerPage.Success.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer created.
        /// </summary>
        public static string AddComputerPage_Success_Title {
            get {
                return ResourceManager.GetString("AddComputerPage.Success.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many active processes should run in the cluster..
        /// </summary>
        public static string AddProgramPage_Active_Description {
            get {
                return ResourceManager.GetString("AddProgramPage.Active.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active processes.
        /// </summary>
        public static string AddProgramPage_Active_Title {
            get {
                return ResourceManager.GetString("AddProgramPage.Active.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique identifier for this program..
        /// </summary>
        public static string AddProgramPage_Name_Description {
            get {
                return ResourceManager.GetString("AddProgramPage.Name.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AddProgramPage_Name_Title {
            get {
                return ResourceManager.GetString("AddProgramPage.Name.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully created..
        /// </summary>
        public static string AddProgramPage_Success_Text {
            get {
                return ResourceManager.GetString("AddProgramPage.Success.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program created.
        /// </summary>
        public static string AddProgramPage_Success_Title {
            get {
                return ResourceManager.GetString("AddProgramPage.Success.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Computer_Delete {
            get {
                return ResourceManager.GetString("Computer.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outsource only.
        /// </summary>
        public static string Computer_Delete_Outsource {
            get {
                return ResourceManager.GetString("Computer.Delete.Outsource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion failed as this computer is running programs, but they can be outsourced to other machines. Would you like to proceed?.
        /// </summary>
        public static string Computer_Delete_Text {
            get {
                return ResourceManager.GetString("Computer.Delete.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully deleted..
        /// </summary>
        public static string ComputerDetailsPage_DeleteSuccess_Text {
            get {
                return ResourceManager.GetString("ComputerDetailsPage.DeleteSuccess.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer deleted.
        /// </summary>
        public static string ComputerDetailsPage_DeleteSuccess_Title {
            get {
                return ResourceManager.GetString("ComputerDetailsPage.DeleteSuccess.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer doesn&apos;t have any running processes..
        /// </summary>
        public static string ComputerDetailsPage_Empty_Description {
            get {
                return ResourceManager.GetString("ComputerDetailsPage.Empty.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No processes.
        /// </summary>
        public static string ComputerDetailsPage_Empty_Title {
            get {
                return ResourceManager.GetString("ComputerDetailsPage.Empty.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        public static string ComputerDetailsPage_Processes {
            get {
                return ResourceManager.GetString("ComputerDetailsPage.Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computers.
        /// </summary>
        public static string Computers {
            get {
                return ResourceManager.GetString("Computers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no computers in this cluster..
        /// </summary>
        public static string ComputersPage_Empty_EmptyText {
            get {
                return ResourceManager.GetString("ComputersPage.Empty.EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no computers matching this filter..
        /// </summary>
        public static string ComputersPage_Empty_FilterText {
            get {
                return ResourceManager.GetString("ComputersPage.Empty.FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No computers.
        /// </summary>
        public static string ComputersPage_Empty_Title {
            get {
                return ResourceManager.GetString("ComputersPage.Empty.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize.
        /// </summary>
        public static string ComputersPage_Menu_Optimize {
            get {
                return ResourceManager.GetString("ComputersPage.Menu.Optimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Usage (%).
        /// </summary>
        public static string ComputersPage_Sort_MemoryPercent {
            get {
                return ResourceManager.GetString("ComputersPage.Sort.MemoryPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ComputersPage_Sort_Name {
            get {
                return ResourceManager.GetString("ComputersPage.Sort.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor Usage (%).
        /// </summary>
        public static string ComputersPage_Sort_ProcessorPercent {
            get {
                return ResourceManager.GetString("ComputersPage.Sort.ProcessorPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The processes running on this computer require more memory capacity!.
        /// </summary>
        public static string Errors_ComputerMoreMemory {
            get {
                return ResourceManager.GetString("Errors.ComputerMoreMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The processes running on this computer require more processor capacity!.
        /// </summary>
        public static string Errors_ComputerMoreProcessor {
            get {
                return ResourceManager.GetString("Errors.ComputerMoreProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A computer already uses this name.
        /// </summary>
        public static string Errors_ComputerNameTaken {
            get {
                return ResourceManager.GetString("Errors.ComputerNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of cpu cores and memory must be positive..
        /// </summary>
        public static string Errors_ComputerPositive {
            get {
                return ResourceManager.GetString("Errors.ComputerPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Errors_Error {
            get {
                return ResourceManager.GetString("Errors.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fix all errors. For more details, see the logs..
        /// </summary>
        public static string Errors_FixFail {
            get {
                return ResourceManager.GetString("Errors.FixFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must fill out all fields!.
        /// </summary>
        public static string Errors_MissingFields {
            get {
                return ResourceManager.GetString("Errors.MissingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer doesn&apos;t have enough resources!.
        /// </summary>
        public static string Errors_NotEnoughResources {
            get {
                return ResourceManager.GetString("Errors.NotEnoughResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some processes that cannot fit any computers! Would you like to optimize anyway?.
        /// </summary>
        public static string Errors_OptimizeCannotFit {
            get {
                return ResourceManager.GetString("Errors.OptimizeCannotFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outsourcing canceled..
        /// </summary>
        public static string Errors_Outsource_Cancel {
            get {
                return ResourceManager.GetString("Errors.Outsource.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outsourcing failed! Please try again later..
        /// </summary>
        public static string Errors_Outsource_Fail {
            get {
                return ResourceManager.GetString("Errors.Outsource.Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s not enough space to completely outsource all processes. Continue anyway?.
        /// </summary>
        public static string Errors_OutsourceNotEnoughSpace {
            get {
                return ResourceManager.GetString("Errors.OutsourceNotEnoughSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no computers or active processes to optimize!.
        /// </summary>
        public static string Errors_OutsourcingNone {
            get {
                return ResourceManager.GetString("Errors.OutsourcingNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s not enough resource on other computers to outsource..
        /// </summary>
        public static string Errors_OutsourcingOther {
            get {
                return ResourceManager.GetString("Errors.OutsourcingOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program already exists in the cluster!.
        /// </summary>
        public static string Errors_ProgramAlreadyExists {
            get {
                return ResourceManager.GetString("Errors.ProgramAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no computers or active processes to spread!.
        /// </summary>
        public static string Errors_SpreadNone {
            get {
                return ResourceManager.GetString("Errors.SpreadNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved to &apos;{0}&apos;..
        /// </summary>
        public static string Export_Success_Text {
            get {
                return ResourceManager.GetString("Export.Success.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export complete.
        /// </summary>
        public static string Export_Success_Title {
            get {
                return ResourceManager.GetString("Export.Success.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter....
        /// </summary>
        public static string FilterPlaceholder {
            get {
                return ResourceManager.GetString("FilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of computers.
        /// </summary>
        public static string GeneratePage_ComputerCount {
            get {
                return ResourceManager.GetString("GeneratePage.ComputerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistent.
        /// </summary>
        public static string GeneratePage_Consistent {
            get {
                return ResourceManager.GetString("GeneratePage.Consistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string GeneratePage_Generate {
            get {
                return ResourceManager.GetString("GeneratePage.Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster path.
        /// </summary>
        public static string GeneratePage_Path {
            get {
                return ResourceManager.GetString("GeneratePage.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose path.
        /// </summary>
        public static string GeneratePage_Path_Choose {
            get {
                return ResourceManager.GetString("GeneratePage.Path.Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of processes.
        /// </summary>
        public static string GeneratePage_ProcessCount {
            get {
                return ResourceManager.GetString("GeneratePage.ProcessCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of programs.
        /// </summary>
        public static string GeneratePage_ProgramCount {
            get {
                return ResourceManager.GetString("GeneratePage.ProgramCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string GeneratePage_Random {
            get {
                return ResourceManager.GetString("GeneratePage.Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spreading number of instances.
        /// </summary>
        public static string GeneratePage_SpreadClusters {
            get {
                return ResourceManager.GetString("GeneratePage.SpreadClusters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t have enough memory capacity ({1}/{2}).
        /// </summary>
        public static string Health_Memory {
            get {
                return ResourceManager.GetString("Health.Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t have enough processes ({1} wanted, {2} active, {3} inactive).
        /// </summary>
        public static string Health_NotEnough {
            get {
                return ResourceManager.GetString("Health.NotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t have enough processor capacity ({1}/{2}).
        /// </summary>
        public static string Health_Processor {
            get {
                return ResourceManager.GetString("Health.Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has too many processes ({1} wanted, {2} active, {3} inactive).
        /// </summary>
        public static string Health_TooMany {
            get {
                return ResourceManager.GetString("Health.TooMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix issues.
        /// </summary>
        public static string HealthPage_Fix {
            get {
                return ResourceManager.GetString("HealthPage.Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All errors fixed ({0} errors).
        /// </summary>
        public static string HealthPage_Fixed {
            get {
                return ResourceManager.GetString("HealthPage.Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No errors were detected in this cluster..
        /// </summary>
        public static string HealthPage_Healthy_Description {
            get {
                return ResourceManager.GetString("HealthPage.Healthy.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy.
        /// </summary>
        public static string HealthPage_Healthy_Title {
            get {
                return ResourceManager.GetString("HealthPage.Healthy.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The issues cannot be solved completely. Would you like to continue anyway?.
        /// </summary>
        public static string HealthPage_NotFixable_Text {
            get {
                return ResourceManager.GetString("HealthPage.NotFixable.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems not fixable.
        /// </summary>
        public static string HealthPage_NotFixable_Title {
            get {
                return ResourceManager.GetString("HealthPage.NotFixable.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string LogDetail_Active {
            get {
                return ResourceManager.GetString("LogDetail.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active programs.
        /// </summary>
        public static string LogDetail_Active_programs {
            get {
                return ResourceManager.GetString("LogDetail.Active programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string LogDetail_Computer {
            get {
                return ResourceManager.GetString("LogDetail.Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computers.
        /// </summary>
        public static string LogDetail_Computers {
            get {
                return ResourceManager.GetString("LogDetail.Computers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        public static string LogDetail_CPU {
            get {
                return ResourceManager.GetString("LogDetail.CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor capacity.
        /// </summary>
        public static string LogDetail_CPU_Capacity {
            get {
                return ResourceManager.GetString("LogDetail.CPU Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor spread percent.
        /// </summary>
        public static string LogDetail_CPU_Spread_Percent {
            get {
                return ResourceManager.GetString("LogDetail.CPU Spread Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Computer.
        /// </summary>
        public static string LogDetail_Destination_computer {
            get {
                return ResourceManager.GetString("LogDetail.Destination computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed processes.
        /// </summary>
        public static string LogDetail_Fixed_Processes {
            get {
                return ResourceManager.GetString("LogDetail.Fixed Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string LogDetail_Host_Computer {
            get {
                return ResourceManager.GetString("LogDetail.Host Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string LogDetail_Instance {
            get {
                return ResourceManager.GetString("LogDetail.Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        public static string LogDetail_Instances {
            get {
                return ResourceManager.GetString("LogDetail.Instances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum percent.
        /// </summary>
        public static string LogDetail_Maximum_Percent {
            get {
                return ResourceManager.GetString("LogDetail.Maximum Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string LogDetail_Memory {
            get {
                return ResourceManager.GetString("LogDetail.Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory capacity.
        /// </summary>
        public static string LogDetail_Memory_Capacity {
            get {
                return ResourceManager.GetString("LogDetail.Memory Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory usage.
        /// </summary>
        public static string LogDetail_Memory_Usage {
            get {
                return ResourceManager.GetString("LogDetail.Memory Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum percent.
        /// </summary>
        public static string LogDetail_Minimum_Percent {
            get {
                return ResourceManager.GetString("LogDetail.Minimum Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LogDetail_Name {
            get {
                return ResourceManager.GetString("LogDetail.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string LogDetail_Path {
            get {
                return ResourceManager.GetString("LogDetail.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process count.
        /// </summary>
        public static string LogDetail_Process_count {
            get {
                return ResourceManager.GetString("LogDetail.Process count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        public static string LogDetail_Processes {
            get {
                return ResourceManager.GetString("LogDetail.Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor usage.
        /// </summary>
        public static string LogDetail_Processor_Usage {
            get {
                return ResourceManager.GetString("LogDetail.Processor Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string LogDetail_Programtypes {
            get {
                return ResourceManager.GetString("LogDetail.Programtypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory spread percent.
        /// </summary>
        public static string LogDetail_RAM_Spread_Percent {
            get {
                return ResourceManager.GetString("LogDetail.RAM Spread Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source computer.
        /// </summary>
        public static string LogDetail_Source_computer {
            get {
                return ResourceManager.GetString("LogDetail.Source computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string LogDetail_Start {
            get {
                return ResourceManager.GetString("LogDetail.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string LogDetail_Type {
            get {
                return ResourceManager.GetString("LogDetail.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All log details.
        /// </summary>
        public static string Logs_AllDetails {
            get {
                return ResourceManager.GetString("Logs.AllDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All log types.
        /// </summary>
        public static string Logs_AllTypes {
            get {
                return ResourceManager.GetString("Logs.AllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all.
        /// </summary>
        public static string Logs_CollapseAll {
            get {
                return ResourceManager.GetString("Logs.CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No logs to show.
        /// </summary>
        public static string Logs_Empty {
            get {
                return ResourceManager.GetString("Logs.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no logs matching this filter..
        /// </summary>
        public static string Logs_Empty_Text {
            get {
                return ResourceManager.GetString("Logs.Empty.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all.
        /// </summary>
        public static string Logs_ExpandAll {
            get {
                return ResourceManager.GetString("Logs.ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate process.
        /// </summary>
        public static string LogType_ActivateProgramInstance {
            get {
                return ResourceManager.GetString("LogType.ActivateProgramInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add computer.
        /// </summary>
        public static string LogType_AddComputer {
            get {
                return ResourceManager.GetString("LogType.AddComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add program.
        /// </summary>
        public static string LogType_AddProgram {
            get {
                return ResourceManager.GetString("LogType.AddProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear processes.
        /// </summary>
        public static string LogType_ClearProgramInstances {
            get {
                return ResourceManager.GetString("LogType.ClearProgramInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close application.
        /// </summary>
        public static string LogType_CloseApplication {
            get {
                return ResourceManager.GetString("LogType.CloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate process.
        /// </summary>
        public static string LogType_DeactivateProgramInstance {
            get {
                return ResourceManager.GetString("LogType.DeactivateProgramInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete computer.
        /// </summary>
        public static string LogType_DeleteComputer {
            get {
                return ResourceManager.GetString("LogType.DeleteComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CSV.
        /// </summary>
        public static string LogType_ExportCSV {
            get {
                return ResourceManager.GetString("LogType.ExportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix issues.
        /// </summary>
        public static string LogType_FixIssues {
            get {
                return ResourceManager.GetString("LogType.FixIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate cluster.
        /// </summary>
        public static string LogType_GenerateCluster {
            get {
                return ResourceManager.GetString("LogType.GenerateCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load cluster.
        /// </summary>
        public static string LogType_LoadCluster {
            get {
                return ResourceManager.GetString("LogType.LoadCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify computer.
        /// </summary>
        public static string LogType_ModifyComputer {
            get {
                return ResourceManager.GetString("LogType.ModifyComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify program.
        /// </summary>
        public static string LogType_ModifyProgram {
            get {
                return ResourceManager.GetString("LogType.ModifyProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move process.
        /// </summary>
        public static string LogType_MoveProgramInstance {
            get {
                return ResourceManager.GetString("LogType.MoveProgramInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open application.
        /// </summary>
        public static string LogType_OpenApplication {
            get {
                return ResourceManager.GetString("LogType.OpenApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize processes.
        /// </summary>
        public static string LogType_OptimizeProgramInstances {
            get {
                return ResourceManager.GetString("LogType.OptimizeProgramInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run process.
        /// </summary>
        public static string LogType_RunProgramInstance {
            get {
                return ResourceManager.GetString("LogType.RunProgramInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown program.
        /// </summary>
        public static string LogType_ShutdownProgram {
            get {
                return ResourceManager.GetString("LogType.ShutdownProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown process.
        /// </summary>
        public static string LogType_ShutdownProgramInstance {
            get {
                return ResourceManager.GetString("LogType.ShutdownProgramInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spread processes.
        /// </summary>
        public static string LogType_SpreadProgramInstances {
            get {
                return ResourceManager.GetString("LogType.SpreadProgramInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string Memory {
            get {
                return ResourceManager.GetString("Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory capacity.
        /// </summary>
        public static string MemoryCapacity {
            get {
                return ResourceManager.GetString("MemoryCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory usage.
        /// </summary>
        public static string MemoryUsage {
            get {
                return ResourceManager.GetString("MemoryUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computers.
        /// </summary>
        public static string Menu_Computers {
            get {
                return ResourceManager.GetString("Menu.Computers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate cluster.
        /// </summary>
        public static string Menu_Generate {
            get {
                return ResourceManager.GetString("Menu.Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster health.
        /// </summary>
        public static string Menu_Health {
            get {
                return ResourceManager.GetString("Menu.Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen folder doesn&apos;t contain a .klaszter file..
        /// </summary>
        public static string Menu_Invalid_Text {
            get {
                return ResourceManager.GetString("Menu.Invalid.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid folder.
        /// </summary>
        public static string Menu_Invalid_Title {
            get {
                return ResourceManager.GetString("Menu.Invalid.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load cluster.
        /// </summary>
        public static string Menu_Load {
            get {
                return ResourceManager.GetString("Menu.Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load another cluster.
        /// </summary>
        public static string Menu_LoadAnother {
            get {
                return ResourceManager.GetString("Menu.LoadAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster logs.
        /// </summary>
        public static string Menu_Logs {
            get {
                return ResourceManager.GetString("Menu.Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster: .
        /// </summary>
        public static string Menu_Path_Label {
            get {
                return ResourceManager.GetString("Menu.Path.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Menu_Path_None {
            get {
                return ResourceManager.GetString("Menu.Path.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        public static string Menu_Processes {
            get {
                return ResourceManager.GetString("Menu.Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string Menu_Programs {
            get {
                return ResourceManager.GetString("Menu.Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully modified..
        /// </summary>
        public static string ModifyComputerPage_Success_Text {
            get {
                return ResourceManager.GetString("ModifyComputerPage.Success.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}.
        /// </summary>
        public static string ModifyComputerPage_Title {
            get {
                return ResourceManager.GetString("ModifyComputerPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully modified..
        /// </summary>
        public static string ModifyProgramPage_Success_Text {
            get {
                return ResourceManager.GetString("ModifyProgramPage.Success.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}.
        /// </summary>
        public static string ModifyProgramPage_Title {
            get {
                return ResourceManager.GetString("ModifyProgramPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string NewInstancePage_Computer {
            get {
                return ResourceManager.GetString("NewInstancePage.Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string NewInstancePage_Program {
            get {
                return ResourceManager.GetString("NewInstancePage.Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string NewInstancePage_Run {
            get {
                return ResourceManager.GetString("NewInstancePage.Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process &apos;{0}&apos; is now running on &apos;{1}&apos;..
        /// </summary>
        public static string NewInstancePage_Success_Text {
            get {
                return ResourceManager.GetString("NewInstancePage.Success.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process started.
        /// </summary>
        public static string NewInstancePage_Success_Title {
            get {
                return ResourceManager.GetString("NewInstancePage.Success.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize.
        /// </summary>
        public static string Optimize_Button {
            get {
                return ResourceManager.GetString("Optimize.Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The optimization was cancelled..
        /// </summary>
        public static string Optimize_Cancel {
            get {
                return ResourceManager.GetString("Optimize.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any inactive process will remain untouched..
        /// </summary>
        public static string Optimize_Inactive {
            get {
                return ResourceManager.GetString("Optimize.Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum percentage.
        /// </summary>
        public static string Optimize_Maximum {
            get {
                return ResourceManager.GetString("Optimize.Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum percentage.
        /// </summary>
        public static string Optimize_Minimum {
            get {
                return ResourceManager.GetString("Optimize.Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the optimal minimum and maximum usage percentage of the computers!.
        /// </summary>
        public static string Optimize_Popup_Title {
            get {
                return ResourceManager.GetString("Optimize.Popup.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spread.
        /// </summary>
        public static string Optimize_Spread {
            get {
                return ResourceManager.GetString("Optimize.Spread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes were spread equally!.
        /// </summary>
        public static string Optimize_Spread_Success {
            get {
                return ResourceManager.GetString("Optimize.Spread.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimizing cannot be done with the given values! Would you like to spread the processes equally?.
        /// </summary>
        public static string Optimize_SpreadQuestion {
            get {
                return ResourceManager.GetString("Optimize.SpreadQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimization was successful!.
        /// </summary>
        public static string Optimize_Success {
            get {
                return ResourceManager.GetString("Optimize.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set optimization values.
        /// </summary>
        public static string Optimize_Title {
            get {
                return ResourceManager.GetString("Optimize.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outsourcing and deletion succeeded!.
        /// </summary>
        public static string Outsourcing_DeleteSuccess {
            get {
                return ResourceManager.GetString("Outsourcing.DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outsourced as many processes as possible! {0} processes remain on &apos;{1}&apos; computer..
        /// </summary>
        public static string Outsourcing_PartialSuccess {
            get {
                return ResourceManager.GetString("Outsourcing.PartialSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outsourcing succeeded! You can delete now the &apos;{0}&apos; safely..
        /// </summary>
        public static string Outsourcing_Success {
            get {
                return ResourceManager.GetString("Outsourcing.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        public static string Processes {
            get {
                return ResourceManager.GetString("Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processes.
        /// </summary>
        public static string ProcessesPage_ComputerTooltip {
            get {
                return ResourceManager.GetString("ProcessesPage.ComputerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no processes matching this filter..
        /// </summary>
        public static string ProcessesPage_Empty_Description {
            get {
                return ResourceManager.GetString("ProcessesPage.Empty.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No processes.
        /// </summary>
        public static string ProcessesPage_Empty_Title {
            get {
                return ResourceManager.GetString("ProcessesPage.Empty.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string ProcessesPage_Sort_Program {
            get {
                return ResourceManager.GetString("ProcessesPage.Sort.Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string ProcessesPage_Sort_Time {
            get {
                return ResourceManager.GetString("ProcessesPage.Sort.Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active only.
        /// </summary>
        public static string ProcessesPage_Status_Active {
            get {
                return ResourceManager.GetString("ProcessesPage.Status.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive only.
        /// </summary>
        public static string ProcessesPage_Status_Inactive {
            get {
                return ResourceManager.GetString("ProcessesPage.Status.Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        public static string Processor {
            get {
                return ResourceManager.GetString("Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor capacity.
        /// </summary>
        public static string ProcessorCapacity {
            get {
                return ResourceManager.GetString("ProcessorCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor usage.
        /// </summary>
        public static string ProcessorUsage {
            get {
                return ResourceManager.GetString("ProcessorUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string Programs {
            get {
                return ResourceManager.GetString("Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested {0} processes.
        /// </summary>
        public static string ProgramsPage_CardRequested {
            get {
                return ResourceManager.GetString("ProgramsPage.CardRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no programs in this cluster..
        /// </summary>
        public static string ProgramsPage_Empty_EmptyText {
            get {
                return ResourceManager.GetString("ProgramsPage.Empty.EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no programs matching this filter..
        /// </summary>
        public static string ProgramsPage_Empty_FilterText {
            get {
                return ResourceManager.GetString("ProgramsPage.Empty.FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No programs.
        /// </summary>
        public static string ProgramsPage_Empty_Title {
            get {
                return ResourceManager.GetString("ProgramsPage.Empty.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested.
        /// </summary>
        public static string ProgramsPage_Requested {
            get {
                return ResourceManager.GetString("ProgramsPage.Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string ProgramsPage_Shutdown {
            get {
                return ResourceManager.GetString("ProgramsPage.Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully shut down..
        /// </summary>
        public static string ProgramsPage_Shutdown_Success {
            get {
                return ResourceManager.GetString("ProgramsPage.Shutdown.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will shut down all {0} processes..
        /// </summary>
        public static string ProgramsPage_Shutdown_Text {
            get {
                return ResourceManager.GetString("ProgramsPage.Shutdown.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut down {0}?.
        /// </summary>
        public static string ProgramsPage_Shutdown_Title {
            get {
                return ResourceManager.GetString("ProgramsPage.Shutdown.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProgramsPage_Sort_Name {
            get {
                return ResourceManager.GetString("ProgramsPage.Sort.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested processes.
        /// </summary>
        public static string ProgramsPage_Sort_Requested {
            get {
                return ResourceManager.GetString("ProgramsPage.Sort.Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        public static string Settings_Darkmode_Title {
            get {
                return ResourceManager.GetString("Settings.Darkmode.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Settings_Language_English {
            get {
                return ResourceManager.GetString("Settings.Language.English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        public static string Settings_Language_Hungarian {
            get {
                return ResourceManager.GetString("Settings.Language.Hungarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language_Title {
            get {
                return ResourceManager.GetString("Settings.Language.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to select a folder.
        /// </summary>
        public static string StartPage_Description {
            get {
                return ResourceManager.GetString("StartPage.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cluster open.
        /// </summary>
        public static string StartPage_Title {
            get {
                return ResourceManager.GetString("StartPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster Management.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window.Title", resourceCulture);
            }
        }
    }
}
