//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cluster.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Cluster.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Settings_Darkmode_Title {
            get {
                return ResourceManager.GetString("Settings.Darkmode.Title", resourceCulture);
            }
        }
        
        public static string Settings_Language_English {
            get {
                return ResourceManager.GetString("Settings.Language.English", resourceCulture);
            }
        }
        
        public static string Settings_Language_Hungarian {
            get {
                return ResourceManager.GetString("Settings.Language.Hungarian", resourceCulture);
            }
        }
        
        public static string Settings_Language_Title {
            get {
                return ResourceManager.GetString("Settings.Language.Title", resourceCulture);
            }
        }
        
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings.Title", resourceCulture);
            }
        }
        
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window.Title", resourceCulture);
            }
        }
        
        public static string Menu_Health {
            get {
                return ResourceManager.GetString("Menu.Health", resourceCulture);
            }
        }
        
        public static string Menu_Computers {
            get {
                return ResourceManager.GetString("Menu.Computers", resourceCulture);
            }
        }
        
        public static string Menu_Processes {
            get {
                return ResourceManager.GetString("Menu.Processes", resourceCulture);
            }
        }
        
        public static string Menu_Programs {
            get {
                return ResourceManager.GetString("Menu.Programs", resourceCulture);
            }
        }
        
        public static string Menu_Logs {
            get {
                return ResourceManager.GetString("Menu.Logs", resourceCulture);
            }
        }
        
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu.Settings", resourceCulture);
            }
        }
        
        public static string Menu_Path_Label {
            get {
                return ResourceManager.GetString("Menu.Path.Label", resourceCulture);
            }
        }
        
        public static string Menu_Path_None {
            get {
                return ResourceManager.GetString("Menu.Path.None", resourceCulture);
            }
        }
        
        public static string Menu_Load {
            get {
                return ResourceManager.GetString("Menu.Load", resourceCulture);
            }
        }
        
        public static string Menu_Generate {
            get {
                return ResourceManager.GetString("Menu.Generate", resourceCulture);
            }
        }
        
        public static string Menu_LoadAnother {
            get {
                return ResourceManager.GetString("Menu.LoadAnother", resourceCulture);
            }
        }
        
        public static string Menu_Invalid_Title {
            get {
                return ResourceManager.GetString("Menu.Invalid.Title", resourceCulture);
            }
        }
        
        public static string Menu_Invalid_Text {
            get {
                return ResourceManager.GetString("Menu.Invalid.Text", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string StartPage_Title {
            get {
                return ResourceManager.GetString("StartPage.Title", resourceCulture);
            }
        }
        
        public static string StartPage_Description {
            get {
                return ResourceManager.GetString("StartPage.Description", resourceCulture);
            }
        }
        
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        public static string AddComputerPage_Name_Title {
            get {
                return ResourceManager.GetString("AddComputerPage.Name.Title", resourceCulture);
            }
        }
        
        public static string AddComputerPage_Name_Description {
            get {
                return ResourceManager.GetString("AddComputerPage.Name.Description", resourceCulture);
            }
        }
        
        public static string ProcessorCapacity {
            get {
                return ResourceManager.GetString("ProcessorCapacity", resourceCulture);
            }
        }
        
        public static string MemoryCapacity {
            get {
                return ResourceManager.GetString("MemoryCapacity", resourceCulture);
            }
        }
        
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        public static string Errors_Error {
            get {
                return ResourceManager.GetString("Errors.Error", resourceCulture);
            }
        }
        
        public static string Errors_MissingFields {
            get {
                return ResourceManager.GetString("Errors.MissingFields", resourceCulture);
            }
        }
        
        public static string AddComputerPage_Success_Title {
            get {
                return ResourceManager.GetString("AddComputerPage.Success.Title", resourceCulture);
            }
        }
        
        public static string AddComputerPage_Success_Text {
            get {
                return ResourceManager.GetString("AddComputerPage.Success.Text", resourceCulture);
            }
        }
        
        public static string AddProgramPage_Name_Title {
            get {
                return ResourceManager.GetString("AddProgramPage.Name.Title", resourceCulture);
            }
        }
        
        public static string AddProgramPage_Name_Description {
            get {
                return ResourceManager.GetString("AddProgramPage.Name.Description", resourceCulture);
            }
        }
        
        public static string AddProgramPage_Active_Title {
            get {
                return ResourceManager.GetString("AddProgramPage.Active.Title", resourceCulture);
            }
        }
        
        public static string AddProgramPage_Active_Description {
            get {
                return ResourceManager.GetString("AddProgramPage.Active.Description", resourceCulture);
            }
        }
        
        public static string ProcessorUsage {
            get {
                return ResourceManager.GetString("ProcessorUsage", resourceCulture);
            }
        }
        
        public static string MemoryUsage {
            get {
                return ResourceManager.GetString("MemoryUsage", resourceCulture);
            }
        }
        
        public static string Errors_ProgramAlreadyExists {
            get {
                return ResourceManager.GetString("Errors.ProgramAlreadyExists", resourceCulture);
            }
        }
        
        public static string AddProgramPage_Success_Title {
            get {
                return ResourceManager.GetString("AddProgramPage.Success.Title", resourceCulture);
            }
        }
        
        public static string AddProgramPage_Success_Text {
            get {
                return ResourceManager.GetString("AddProgramPage.Success.Text", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string Programs {
            get {
                return ResourceManager.GetString("Programs", resourceCulture);
            }
        }
        
        public static string Processes {
            get {
                return ResourceManager.GetString("Processes", resourceCulture);
            }
        }
        
        public static string ComputerDetailsPage_Empty_Title {
            get {
                return ResourceManager.GetString("ComputerDetailsPage.Empty.Title", resourceCulture);
            }
        }
        
        public static string ComputerDetailsPage_Empty_Description {
            get {
                return ResourceManager.GetString("ComputerDetailsPage.Empty.Description", resourceCulture);
            }
        }
        
        public static string Processor {
            get {
                return ResourceManager.GetString("Processor", resourceCulture);
            }
        }
        
        public static string Memory {
            get {
                return ResourceManager.GetString("Memory", resourceCulture);
            }
        }
        
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        public static string ComputerDetailsPage_Processes {
            get {
                return ResourceManager.GetString("ComputerDetailsPage.Processes", resourceCulture);
            }
        }
        
        public static string ComputerDetailsPage_DeleteSuccess_Title {
            get {
                return ResourceManager.GetString("ComputerDetailsPage.DeleteSuccess.Title", resourceCulture);
            }
        }
        
        public static string ComputerDetailsPage_DeleteSuccess_Text {
            get {
                return ResourceManager.GetString("ComputerDetailsPage.DeleteSuccess.Text", resourceCulture);
            }
        }
        
        public static string Outsourcing_DeleteSuccess {
            get {
                return ResourceManager.GetString("Outsourcing.DeleteSuccess", resourceCulture);
            }
        }
        
        public static string FilterPlaceholder {
            get {
                return ResourceManager.GetString("FilterPlaceholder", resourceCulture);
            }
        }
        
        public static string ComputersPage_Sort_Name {
            get {
                return ResourceManager.GetString("ComputersPage.Sort.Name", resourceCulture);
            }
        }
        
        public static string ComputersPage_Sort_ProcessorPercent {
            get {
                return ResourceManager.GetString("ComputersPage.Sort.ProcessorPercent", resourceCulture);
            }
        }
        
        public static string ComputersPage_Sort_MemoryPercent {
            get {
                return ResourceManager.GetString("ComputersPage.Sort.MemoryPercent", resourceCulture);
            }
        }
        
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        public static string ComputersPage_Menu_Optimize {
            get {
                return ResourceManager.GetString("ComputersPage.Menu.Optimize", resourceCulture);
            }
        }
        
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        public static string ComputersPage_Empty_Title {
            get {
                return ResourceManager.GetString("ComputersPage.Empty.Title", resourceCulture);
            }
        }
        
        public static string ComputersPage_Empty_EmptyText {
            get {
                return ResourceManager.GetString("ComputersPage.Empty.EmptyText", resourceCulture);
            }
        }
        
        public static string ComputersPage_Empty_FilterText {
            get {
                return ResourceManager.GetString("ComputersPage.Empty.FilterText", resourceCulture);
            }
        }
        
        public static string Optimize_Title {
            get {
                return ResourceManager.GetString("Optimize.Title", resourceCulture);
            }
        }
        
        public static string Optimize_Button {
            get {
                return ResourceManager.GetString("Optimize.Button", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Optimize_SpreadQuestion {
            get {
                return ResourceManager.GetString("Optimize.SpreadQuestion", resourceCulture);
            }
        }
        
        public static string Optimize_Spread {
            get {
                return ResourceManager.GetString("Optimize.Spread", resourceCulture);
            }
        }
        
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        public static string Optimize_Spread_Success {
            get {
                return ResourceManager.GetString("Optimize.Spread.Success", resourceCulture);
            }
        }
        
        public static string Optimize_Success {
            get {
                return ResourceManager.GetString("Optimize.Success", resourceCulture);
            }
        }
        
        public static string GeneratePage_ComputerCount {
            get {
                return ResourceManager.GetString("GeneratePage.ComputerCount", resourceCulture);
            }
        }
        
        public static string GeneratePage_ProgramCount {
            get {
                return ResourceManager.GetString("GeneratePage.ProgramCount", resourceCulture);
            }
        }
        
        public static string GeneratePage_ProcessCount {
            get {
                return ResourceManager.GetString("GeneratePage.ProcessCount", resourceCulture);
            }
        }
        
        public static string GeneratePage_Path {
            get {
                return ResourceManager.GetString("GeneratePage.Path", resourceCulture);
            }
        }
        
        public static string GeneratePage_Path_Choose {
            get {
                return ResourceManager.GetString("GeneratePage.Path.Choose", resourceCulture);
            }
        }
        
        public static string GeneratePage_Generate {
            get {
                return ResourceManager.GetString("GeneratePage.Generate", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string ModifyComputerPage_Title {
            get {
                return ResourceManager.GetString("ModifyComputerPage.Title", resourceCulture);
            }
        }
        
        public static string ModifyComputerPage_Success_Text {
            get {
                return ResourceManager.GetString("ModifyComputerPage.Success.Text", resourceCulture);
            }
        }
        
        public static string ModifyProgramPage_Title {
            get {
                return ResourceManager.GetString("ModifyProgramPage.Title", resourceCulture);
            }
        }
        
        public static string ModifyProgramPage_Success_Text {
            get {
                return ResourceManager.GetString("ModifyProgramPage.Success.Text", resourceCulture);
            }
        }
        
        public static string NewInstancePage_Program {
            get {
                return ResourceManager.GetString("NewInstancePage.Program", resourceCulture);
            }
        }
        
        public static string NewInstancePage_Computer {
            get {
                return ResourceManager.GetString("NewInstancePage.Computer", resourceCulture);
            }
        }
        
        public static string NewInstancePage_Run {
            get {
                return ResourceManager.GetString("NewInstancePage.Run", resourceCulture);
            }
        }
        
        public static string Errors_NotEnoughResources {
            get {
                return ResourceManager.GetString("Errors.NotEnoughResources", resourceCulture);
            }
        }
        
        public static string NewInstancePage_Success_Title {
            get {
                return ResourceManager.GetString("NewInstancePage.Success.Title", resourceCulture);
            }
        }
        
        public static string NewInstancePage_Success_Text {
            get {
                return ResourceManager.GetString("NewInstancePage.Success.Text", resourceCulture);
            }
        }
        
        public static string ProcessesPage_Status_Active {
            get {
                return ResourceManager.GetString("ProcessesPage.Status.Active", resourceCulture);
            }
        }
        
        public static string ProcessesPage_Status_Inactive {
            get {
                return ResourceManager.GetString("ProcessesPage.Status.Inactive", resourceCulture);
            }
        }
        
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        public static string ProcessesPage_Sort_Program {
            get {
                return ResourceManager.GetString("ProcessesPage.Sort.Program", resourceCulture);
            }
        }
        
        public static string ProcessesPage_Sort_Time {
            get {
                return ResourceManager.GetString("ProcessesPage.Sort.Time", resourceCulture);
            }
        }
        
        public static string Computers {
            get {
                return ResourceManager.GetString("Computers", resourceCulture);
            }
        }
        
        public static string ProcessesPage_Empty_Title {
            get {
                return ResourceManager.GetString("ProcessesPage.Empty.Title", resourceCulture);
            }
        }
        
        public static string ProcessesPage_Empty_Description {
            get {
                return ResourceManager.GetString("ProcessesPage.Empty.Description", resourceCulture);
            }
        }
        
        public static string ProgramsPage_Sort_Name {
            get {
                return ResourceManager.GetString("ProgramsPage.Sort.Name", resourceCulture);
            }
        }
        
        public static string ProgramsPage_Sort_Requested {
            get {
                return ResourceManager.GetString("ProgramsPage.Sort.Requested", resourceCulture);
            }
        }
        
        public static string ProgramsPage_Requested {
            get {
                return ResourceManager.GetString("ProgramsPage.Requested", resourceCulture);
            }
        }
        
        public static string ProgramsPage_CardRequested {
            get {
                return ResourceManager.GetString("ProgramsPage.CardRequested", resourceCulture);
            }
        }
        
        public static string ProgramsPage_Empty_Title {
            get {
                return ResourceManager.GetString("ProgramsPage.Empty.Title", resourceCulture);
            }
        }
        
        public static string ProgramsPage_Empty_FilterText {
            get {
                return ResourceManager.GetString("ProgramsPage.Empty.FilterText", resourceCulture);
            }
        }
        
        public static string ProgramsPage_Empty_EmptyText {
            get {
                return ResourceManager.GetString("ProgramsPage.Empty.EmptyText", resourceCulture);
            }
        }
        
        public static string ProgramsPage_Shutdown_Title {
            get {
                return ResourceManager.GetString("ProgramsPage.Shutdown.Title", resourceCulture);
            }
        }
        
        public static string ProgramsPage_Shutdown_Text {
            get {
                return ResourceManager.GetString("ProgramsPage.Shutdown.Text", resourceCulture);
            }
        }
        
        public static string ProgramsPage_Shutdown {
            get {
                return ResourceManager.GetString("ProgramsPage.Shutdown", resourceCulture);
            }
        }
        
        public static string ProgramsPage_Shutdown_Success {
            get {
                return ResourceManager.GetString("ProgramsPage.Shutdown.Success", resourceCulture);
            }
        }
        
        public static string HealthPage_Fix {
            get {
                return ResourceManager.GetString("HealthPage.Fix", resourceCulture);
            }
        }
        
        public static string HealthPage_Healthy_Title {
            get {
                return ResourceManager.GetString("HealthPage.Healthy.Title", resourceCulture);
            }
        }
        
        public static string HealthPage_Healthy_Description {
            get {
                return ResourceManager.GetString("HealthPage.Healthy.Description", resourceCulture);
            }
        }
        
        public static string Errors_FixFail {
            get {
                return ResourceManager.GetString("Errors.FixFail", resourceCulture);
            }
        }
        
        public static string HealthPage_Fixed {
            get {
                return ResourceManager.GetString("HealthPage.Fixed", resourceCulture);
            }
        }
        
        public static string Logs_Empty {
            get {
                return ResourceManager.GetString("Logs.Empty", resourceCulture);
            }
        }
        
        public static string Logs_Empty_Text {
            get {
                return ResourceManager.GetString("Logs.Empty.Text", resourceCulture);
            }
        }
        
        public static string Logs_AllTypes {
            get {
                return ResourceManager.GetString("Logs.AllTypes", resourceCulture);
            }
        }
        
        public static string Logs_AllDetails {
            get {
                return ResourceManager.GetString("Logs.AllDetails", resourceCulture);
            }
        }
        
        public static string Logs_ExpandAll {
            get {
                return ResourceManager.GetString("Logs.ExpandAll", resourceCulture);
            }
        }
    }
}
