site_name: Kibirod, kolega Dokumentáció
site_url: https://konlll.github.io/dusza2025/

nav:
  - Kezdőlap: "index.md"
  - Bevezetés:
      - "bevezetes/programrol.md"
      - "bevezetes/licenszek.md"
  - Felhasználói dokumentáció:
      - "felhasznaloi/mukodes.md"
      - "felhasznaloi/klaszter.md"
      - "felhasznaloi/beallitasok.md"
      - "felhasznaloi/szamitogep.md"
      - "felhasznaloi/folyamat.md"
      - "felhasznaloi/program.md"
      - "felhasznaloi/naplozas.md"
      - "felhasznaloi/beallitasok.md"
  - Fejlesztői dokumentáció:
      - "fejlesztoi/fejlesztes.md"
      - "fejlesztoi/futtatas.md"
      - "fejlesztoi/szerkezet.md"
      - "fejlesztoi/technologiak.md"
      - "fejlesztoi/dokumentáció.md"

theme:
  name: material
  language: hu
  icon:
    logo: material/server
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Váltás világos módra
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Váltás sötét módra
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Váltás automata módra
  features:
    - navigation.tracking
    - navigation.sections
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight

extra:
  generator: false
copyright: Copyright &copy; 2025 Kibirod, kolega

plugins:
  - search:
      lang: hu
  - offline:
      enabled: !ENV [OFFLINE, false]

markdown_extensions:
  - abbr
  - admonition
  - toc
  - tables
